# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
    ]
