# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-17 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_remove_users_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=200),
        ),
    ]
